### ISSUE TITLE
Use HotelsCombined APIs

### ISSUE THREAD

**Issue by SorataYuu** [CS3103-Group17/Project#10]
See: https://affiliates.hotelscombined.com/

**Comment by AdamGan** [comment]
HotelsCombined (data feeds): sent request, probably will be rejected.
Expedia: User registration closed
TripAdvisor: sent request, probably will be rejected. (+heard it's quite useless)
Booking: Need to send request

**Comment by AdamGan** [comment]
TIXIK: sent request

**Comment by AdamGan** [comment]
Currently using Expedia.

HotelsCombined, TripAdvisor: Rejected.
TIXIK: no response
