### ISSUE TITLE
Crawl EBay's API

### ISSUE THREAD

**Issue by SorataYuu** [CS3103-Group17/Project#3]
See: https://go.developer.ebay.com/what-ebay-api

**Comment by AdamGan** [comment]
Java 1.6 ships with SAAJ 1.3, JAXB 2.0, and JAXP 1.4 (a custom version of Xerces and Xalan). Overriding these libraries by putting different version on the classpath will result in various classloading issues, or exceptions in org.apache.xml.serializer.ToXMLSAXHandler. The only option for using more recent versions is to put the newer version in the endorsed directory.

http://docs.spring.io/spring-ws/sites/1.5/faq.html#java-1.6

EDIT: Nvm, got it to work without the overriding issues
