### ISSUE TITLE
Crawl Facebook

### ISSUE THREAD

**Issue by SorataYuu** [CS3103-Group17/Project#6]
See: https://www.norconex.com/how-to-crawl-facebook/
See: http://www.oneminuteinfo.com/2015/06/use-api-to-get-fb-comments-plugin-posts.html

**Comment by RyanAlexanderH** [comment]
using restfb instead of norconex

**Comment by RyanAlexanderH** [comment]
done with the facebook crawler. i want to test it on the UI, should I do it myself (might take a while to understand the UI and might break it)? or someone else want to test it on the UI for the fb crawler?

edit: nvm done integrating it with the ui
